---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Smoke test
      command: terraform version
      register: result
      changed_when: False

    - debug: msg="{{ result.stdout }}"

    - name: Test terraform is installed
      assert:
        that:
          - result.rc == 0
